# Generated by Django 4.2.4 on 2023-09-25 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0002_rename_registrar_register_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='imagen',
            field=models.ImageField(upload_to='avatar'),
        ),
    ]
